"""Initial Schema

Revision ID: 581f8daee484
Revises: None
Create Date: 2013-08-21 22:45:08.572018

"""

# revision identifiers, used by Alembic.
revision = '581f8daee484'
down_revision = None

from alembic import op
import sqlalchemy as sa

from feedduty.models import JSONEncodedDict


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=60), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=60), nullable=True),
    sa.Column('email', sa.Unicode(length=60), nullable=True),
    sa.Column('first_name', sa.Unicode(length=60), nullable=True),
    sa.Column('last_name', sa.Unicode(length=60), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('settings', JSONEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_tag_lookup',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_table('feeds',
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=60), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('settings', JSONEncodedDict(), nullable=True),
    sa.Column('url', sa.Unicode(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id')
    )
    op.create_table('feed_tag_lookup',
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.feed_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'tag_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_tag_lookup')
    op.drop_table('feeds')
    op.drop_table('user_tag_lookup')
    op.drop_table('users')
    op.drop_table('tags')
    ### end Alembic commands ###
